import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ThemeToggle } from "@/components/theme-toggle";
import Link from "next/link";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen bg-background font-sans antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="relative flex min-h-screen flex-col">
            <header className="sticky top-0 z-50 w-full border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
              <div className="container flex h-14 items-center mx-auto">
                <div className="flex-1">
                  <h1 className="text-xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-blue-600 to-purple-600">
                    VoteUp
                  </h1>
                </div>
                <div className="flex items-center space-x-2">
                  <ThemeToggle />
                </div>
              </div>
            </header>
            <main className="flex-1">{children}</main>
            {/* Footer */}
            <footer className="border-t border-foreground/10 bg-background/50 backdrop-blur-sm">
              <div className="container mx-auto px-4 py-16">
                {/* Main Footer Content */}
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8 mb-12">
                  {/* Company Info */}
                  <div>
                    <h3 className="font-bold text-lg mb-4">VoteUp</h3>
                    <p className="text-sm text-muted-foreground mb-4">
                      Your Community-Driven Content Ranking Platform. Join us in
                      shaping the future of online discussions.
                    </p>
                  </div>

                  {/* Quick Links */}
                  <div>
                    <h3 className="font-bold text-lg mb-4">Quick Links</h3>
                    <ul className="space-y-2">
                      <li>
                        <Link
                          href="/about"
                          className="text-sm text-muted-foreground hover:text-foreground transition"
                        >
                          About Us
                        </Link>
                      </li>
                      <li>
                        <Link
                          href="/features"
                          className="text-sm text-muted-foreground hover:text-foreground transition"
                        >
                          Features
                        </Link>
                      </li>
                      <li>
                        <Link
                          href="/pricing"
                          className="text-sm text-muted-foreground hover:text-foreground transition"
                        >
                          Pricing
                        </Link>
                      </li>
                    </ul>
                  </div>

                  {/* Resources */}
                  <div>
                    <h3 className="font-bold text-lg mb-4">Resources</h3>
                    <ul className="space-y-2">
                      <li>
                        <Link
                          href="/docs"
                          className="text-sm text-muted-foreground hover:text-foreground transition"
                        >
                          Documentation
                        </Link>
                      </li>
                      <li>
                        <Link
                          href="/blog"
                          className="text-sm text-muted-foreground hover:text-foreground transition"
                        >
                          Blog
                        </Link>
                      </li>
                      <li>
                        <Link
                          href="/support"
                          className="text-sm text-muted-foreground hover:text-foreground transition"
                        >
                          Support
                        </Link>
                      </li>
                    </ul>
                  </div>

                  {/* Tech Stack */}
                  <div>
                    <h3 className="font-bold text-lg mb-4">Built With</h3>
                    <div className="flex flex-col space-y-4">
                      <Image
                        src="/next.svg"
                        alt="Next.js"
                        width={100}
                        height={25}
                        className="dark:invert"
                      />
                      <Image
                        src="/vercel.svg"
                        alt="Vercel"
                        width={100}
                        height={25}
                        className="dark:invert"
                      />
                      <div className="flex space-x-4">
                        <span className="text-sm text-muted-foreground">
                          Prisma
                        </span>
                        <span className="text-sm text-muted-foreground">•</span>
                        <span className="text-sm text-muted-foreground">
                          PostgreSQL
                        </span>
                      </div>
                    </div>
                  </div>
                </div>

                {/* Bottom Bar */}
                <div className="pt-8 border-t border-foreground/10">
                  <div className="flex flex-col md:flex-row justify-between items-center space-y-4 md:space-y-0">
                    <div className="text-sm text-muted-foreground">
                      © {new Date().getFullYear()} VoteUp. All rights reserved.
                    </div>
                    <div className="flex space-x-6">
                      <Link
                        href="/privacy"
                        className="text-sm text-muted-foreground hover:text-foreground transition"
                      >
                        Privacy Policy
                      </Link>
                      <Link
                        href="/terms"
                        className="text-sm text-muted-foreground hover:text-foreground transition"
                      >
                        Terms of Service
                      </Link>
                    </div>
                  </div>
                </div>
              </div>
            </footer>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
